version: '3.4'
services:
  api:
    build: .
    volumes:
          - ".:/usr/src/api"
          - "/usr/src/api/node_modules"
    ports:
          - "8080:8080"
          - "9222:9222"
          - "9221:9221"
    expose:
          - "9222"
          - "9221"
    entrypoint: ["npm", "run", "debug"]
    restart: always
  worker:
    build: .
    volumes:
          - ".:/usr/src/worker"
          - "/usr/src/worker/node_modules"
    expose:
          - "9224"
          - "9223"
    entrypoint: ["npm", "run", "debug:worker"]
    restart: always
